language: node_js
node_js:
  - '12.18.0'
script:
  - "npm run test"
notifications:
  email:
    recipients:
      - juancsch@gmail.com
    on_success: change
    on_failure: always
before_install:
  - pip install --user codecov
after_success:
  - codecov --file backend/coverage/lcov.info --disable search
